PMM-6432 Install operators.
Percona-Lab/pmm-submodules pull request #1773
Opened 2021-05-13 21:08 UTC by BupycHuk

2021-05-14 10:39 UTC, EvgeniyPatlan requested changes

2021-05-14 10:39 UTC, EvgeniyPatlan commented on build/rpmbuild-docker/Dockerfile
>  ENV GO_CHECKSUM 0d142143794721bb63ce6c8a6180c4062bcf8ef4715e7d6d6609f3a8282629b3
go checksum must be updated too

2021-05-14 13:30 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-1773-99cfd95
client docker - perconalab/pmm-client-fb:PR-1773-99cfd95
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1773-99cfd95.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1773-99cfd95&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1773-99cfd95.tar.gz

2021-05-14 14:36 UTC, JNKPercona commented
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/8445/

2021-05-17 10:08 UTC, jprukner commented on build/rpmbuild-docker/Dockerfile
>  ENV GO_CHECKSUM 0d142143794721bb63ce6c8a6180c4062bcf8ef4715e7d6d6609f3a8282629b3
done

2021-05-17 10:10 UTC, jprukner commented
UI tests failing are not related to changes made.

2021-05-19 10:39 UTC, puneet0191 submitted a review, later dismissed

2021-05-19 10:45 UTC, EvgeniyPatlan requested changes

2021-05-19 10:45 UTC, EvgeniyPatlan commented on build/bin/vars
> +rpmbuild_docker_image=${RPMBUILD_DOCKER_IMAGE:-perconalab/rpmbuild:2-go1.16}
Such change shouldn't go to production. we need to build rpmbuild docker image with tag 2

2021-05-19 10:51 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-1773-99cfd95
client docker - perconalab/pmm-client-fb:PR-1773-99cfd95
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1773-99cfd95.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1773-99cfd95&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1773-99cfd95.tar.gz

2021-05-19 10:54 UTC, EvgeniyPatlan approved these changes

2021-05-19 11:00 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-1773-0762344
client docker - perconalab/pmm-client-fb:PR-1773-0762344
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1773-0762344.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1773-0762344&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1773-0762344.tar.gz

2021-05-19 11:03 UTC, merged

2021-05-19 11:14 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-1773-145ea07
client docker - perconalab/pmm-client-fb:PR-1773-145ea07
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1773-145ea07.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1773-145ea07&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1773-145ea07.tar.gz

2021-05-19 11:52 UTC, JNKPercona commented
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/8531/

2021-05-19 11:55 UTC, JNKPercona commented
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/8532/

2021-05-19 12:02 UTC, JNKPercona commented
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/8533/