PMM-8040 add yum cache cleanup
Percona-Lab/pmm-submodules pull request #1845
Opened 2021-06-10 13:08 UTC by nikita-b

2021-06-10 13:33 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-1845-b126998
client docker - perconalab/pmm-client-fb:PR-1845-b126998
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1845-b126998.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1845-b126998&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1845-b126998.tar.gz

2021-06-10 15:01 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-1845-f13d4a9
client docker - perconalab/pmm-client-fb:PR-1845-f13d4a9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1845-f13d4a9.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1845-f13d4a9&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1845-f13d4a9.tar.gz

2021-06-10 15:48 UTC, JNKPercona commented
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/7167/

2021-06-10 15:48 UTC, JNKPercona commented
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/8770/

2021-06-11 06:28 UTC, atymchuk requested changes

2021-06-11 06:28 UTC, atymchuk commented on build/pmm-server-docker/Dockerfile
> +CMD ["/opt/entrypoint.sh"]
@nikita-b I guess this is autoformat getting in your way :)

2021-06-11 08:27 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-1845-91cd351
client docker - perconalab/pmm-client-fb:PR-1845-91cd351
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1845-91cd351.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1845-91cd351&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1845-91cd351.tar.gz

2021-06-14 09:04 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-1845-d5cb7c3
client docker - perconalab/pmm-client-fb:PR-1845-d5cb7c3
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1845-d5cb7c3.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1845-d5cb7c3&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1845-d5cb7c3.tar.gz

2021-06-14 09:06 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-1845-7c585c2
client docker - perconalab/pmm-client-fb:PR-1845-7c585c2
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1845-7c585c2.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1845-7c585c2&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1845-7c585c2.tar.gz

2021-06-16 12:36 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-1845-192b572
client docker - perconalab/pmm-client-fb:PR-1845-192b572
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1845-192b572.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-1845-192b572&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-1845-192b572.tar.gz

2021-06-16 13:23 UTC, JNKPercona commented
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/7214/

2021-06-16 13:23 UTC, JNKPercona commented
UI tests have failed, Please check: UI: https://pmm.cd.percona.com/job/pmm2-ui-tests/8841/

2021-06-25 14:46 UTC, closed without merging