PMM-8874 Updated modules for PMM 2.23
Percona-Lab/pmm-submodules pull request #2067
Opened 2021-10-04 23:27 UTC by percona-csalguero

Updated mongodb_exporter, postgres_exporter and toolkit.
Not included yet because we didn't talk about creating a new release for these exporters.

- proxysql_exporter: release-1.1.2
- rds_exporter: release-0.7.2

I made the branches with the changes. Not need to test because they are based on the corresponding master braches but there were not official releases for proxysql_exporter rds_exporter even when we have changes.

2021-10-04 23:50 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-2067-eef6a54
client docker - perconalab/pmm-client-fb:PR-2067-eef6a54
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2067-eef6a54.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2067-eef6a54&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2067-eef6a54.tar.gz

2021-10-05 08:07 UTC, denisok approved these changes

2021-10-05 08:11 UTC, denisok requested changes

2021-10-05 08:11 UTC, denisok commented on .gitmodules
> +	branch = release-0.4.8
https://github.com/percona/postgres_exporter/pull/51

this probably should be merged to master and master stay ?

2021-10-05 10:42 UTC, denisok approved these changes

2021-10-05 10:43 UTC, BupycHuk approved these changes

2021-10-05 10:44 UTC, merged

2021-10-05 11:01 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-2067-9d7204e
client docker - perconalab/pmm-client-fb:PR-2067-9d7204e
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2067-9d7204e.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2067-9d7204e&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2067-9d7204e.tar.gz