PMM-7 create remote branch
Percona-Lab/pmm-submodules pull request #2334
Opened 2022-02-09 11:44 UTC by BupycHuk

2022-02-09 12:07 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-2334-6986d9c
client docker - perconalab/pmm-client-fb:PR-2334-6986d9c
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2334-6986d9c.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2334-6986d9c&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2334-6986d9c.tar.gz

2022-02-09 15:52 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-2334-ec8f2e9
client docker - perconalab/pmm-client-fb:PR-2334-ec8f2e9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2334-ec8f2e9.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2334-ec8f2e9&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2334-ec8f2e9.tar.gz

2022-02-13 15:36 UTC, nikita-b requested changes

2022-02-13 15:36 UTC, nikita-b commented on ci.py
> +            logging.warning('Failed to push %s. This could be due to no matching upstream branch.', branch_name)
```suggestion
            logging.warning(f'Failed to push {branch_name}. This could be due to no matching upstream branch.')
```

2022-02-13 15:36 UTC, nikita-b commented on ci.py
> +            logging.info('Reattempting to push %s using a lower-level command which also sets upstream branch.', branch_name)
```suggestion
            logging.info(f'Reattempting to push {branch_name} using a lower-level command which also sets upstream branch.')
```

2022-02-13 15:36 UTC, nikita-b commented on ci.py
> +            logging.info('Push output was: %s', push_output)
```suggestion
            logging.info(f'Push output was: {push_output}')
```

2022-03-21 14:18 UTC, nikita-b approved these changes

2022-03-21 15:05 UTC, merged