PMM-10247 Forced to use install_tarball from its parent directory
Percona-Lab/pmm-submodules pull request #2613
Opened 2022-06-29 16:32 UTC by cezmunsta

[PMM-10247](https://jira.percona.com/browse/PMM-10247)

2022-06-29 16:34 UTC, cezmunsta commented
@nikita-b presuming that there is no need for a feature branch for this type of change, let me know if one is needed

2022-06-30 17:17 UTC, nikita-b approved these changes

2022-07-04 03:57 UTC, EvgeniyPatlan requested changes

2022-07-04 03:57 UTC, EvgeniyPatlan commented on build/bin/install_tarball
> +cd - || true
better to save current directory and then just remove to it.
as in future there could be another `cd` command and we would easily return into incorrect directory

2022-07-04 09:21 UTC, cezmunsta commented on build/bin/install_tarball
> +cd - || true
@EvgeniyPatlan do you really see the chance of needing another `cd`?

2022-07-05 09:54 UTC, EvgeniyPatlan approved these changes

2022-07-07 12:17 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-2613-a67c1c9
client docker - perconalab/pmm-client-fb:PR-2613-a67c1c9
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2613-a67c1c9.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2613-a67c1c9&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2613-a67c1c9.tar.gz

2022-07-07 12:58 UTC, JNKPercona commented
API tests have failed, Please check: API: https://pmm.cd.percona.com/job/pmm2-api-tests/10578/

2022-07-19 07:16 UTC, merged