Pmm 11330
Percona-Lab/pmm-submodules pull request #3048
Opened 2023-02-07 12:36 UTC by peterSirotnak

https://jira.percona.com/browse/PMM-0

- [ ] Links to relevant pull requests

2023-02-07 12:54 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-3048-034f592
client docker - perconalab/pmm-client-fb:PR-3048-034f592
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3048-034f592.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3048-034f592&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3048-034f592.tar.gz

2023-02-14 14:23 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-3048-d79bcb0
client docker - perconalab/pmm-client-fb:PR-3048-d79bcb0
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3048-d79bcb0.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3048-d79bcb0&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3048-d79bcb0.tar.gz

2023-02-21 08:56 UTC, yurkovychv requested changes

2023-02-21 08:56 UTC, yurkovychv commented on .github/workflows/pmm2-testsuite.yml
> +          sudo npm install
please move the `install` commands to a separate step in the beginning. And use `sudo npm ci`

2023-02-21 10:51 UTC, JNKPercona commented
server docker - perconalab/pmm-server-fb:PR-3048-92a712b
client docker - perconalab/pmm-client-fb:PR-3048-92a712b
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3048-92a712b.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-3048-92a712b&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-3048-92a712b.tar.gz

2023-02-21 11:24 UTC, peterSirotnak commented on .github/workflows/pmm2-testsuite.yml
> +          sudo npm install
Moved.

2023-02-24 16:15 UTC, yurkovychv approved these changes

2023-02-27 11:03 UTC, merged